name: Deploy project
# trigger when push
on: push
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Get code
      # Uses: sử dụng actions
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
      # npm ci: tải phiên bản đúng với trong package
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    # Chỉ chạy khi test job hoàn thành
    # Có thể để trong [] khi cần thêm nhiều jobs
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
      # Uses: sử dụng actions
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
      # npm ci: tải phiên bản đúng với trong package
        run: npm ci
      - name: Build project
        run: npm run build
      # Deploy lên một host nào đó nếu có
      - name: Deploy
        run: echo "Deploying ...."