name: Output information
on: workflow_dispatch
jobs:
  info: 
    runs-on: ubuntu-latest
    steps:
      - name: Output github context
      # toJSON: chuyển metadata thành dạng JSON
        run: echo "${{ toJSON(github) }}"
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
