name: Test project
# trigger when push
on: push
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Get code
      # Uses: sử dụng actions
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
      # npm ci: tải phiên bản đúng với trong package
        run: npm ci
      - name: Run tests
        run: npm test